### ISSUE TITLE
Abbvie - Signal Data Module - dev

### ISSUE THREAD

**Issue by labkey-klum** [LabKey/signalData#21]
[Spec](https://docs.google.com/document/d/1Y_C3VtTCHfvqMwIaT2qcxWbypI3RTv8wtVPcaAq__Dk/edit?usp=sharing)
[Github epic](https://github.com/LabKey/kanban/issues/234)
[Feature branch](https://github.com/LabKey/signalData/tree/fb_signal_data)

### Tasks 📌 
- [x] Unarchive module
- [x] Misc module updates
- [x] Fix inline scripts (CSP)
- [x] Support for different delimiter types on data import.
- [x] Flexibility when interpreting metadata information. 
- [x] Redirect after import.
- [x] Create distribution
- [x] Configure test suite on TeamCity
- [x]  Feature verification - .5hr @vn929 
- [x]  Manual test plan - 1hr @labkey-klum 
- [x]  Manual testing - 2hr @labkey-chrisj 
- [x]  Code review - 1hr @labkey-ians
